package slackkit

import (
	"encoding/json"
	"testing"

	"github.com/maxatome/go-testdeep/td"
)

func TestNewMessage_BuildsRichBlockKitPayload(t *testing.T) {
	message, err := NewMessage(
		"Deploy finished.",
		NewHeader("Deploy finished", true, WithBlockID("title")),
		NewMarkdownSection(
			"*Status:* successful",
			WithBlockID("summary"),
			WithExpand(true),
			WithAccessory(NewImageElement("https://example.com/deploy.png", "Deploy chart")),
		),
		NewSectionFields(
			[]Text{
				NewMarkdownText("*Environment*\nprod", WithVerbatim(true)),
				NewMarkdownText("*Duration*\n42s"),
			},
			WithBlockID("facts"),
		),
		NewImageBlock(
			"https://example.com/screenshot.png",
			"Deployment screenshot",
			WithImageTitle("Deployment details", true),
		),
		NewContext(
			NewContextImage("https://example.com/icon.png", "App icon"),
			NewContextText(NewMarkdownText("Generated by *servekit*")),
		),
		NewActions(
			NewButton(
				"Open dashboard",
				"open_dashboard",
				WithButtonStyle(PrimaryButton),
				WithButtonValue("deploy-123"),
				WithButtonURL("https://example.com/deploys/123"),
				WithButtonAccessibilityLabel("Open deployment dashboard"),
			),
		),
	)

	td.CmpNoError(t, err)

	payload, err := json.Marshal(message)
	td.CmpNoError(t, err)

	var got any
	err = json.Unmarshal(payload, &got)
	td.CmpNoError(t, err)

	td.Cmp(t, got, td.JSON(`{
		"text": "Deploy finished.",
		"blocks": [
			{
				"type": "header",
				"block_id": "title",
				"text": {
					"type": "plain_text",
					"text": "Deploy finished",
					"emoji": true
				}
			},
			{
				"type": "section",
				"block_id": "summary",
				"text": {
					"type": "mrkdwn",
					"text": "*Status:* successful"
				},
				"accessory": {
					"type": "image",
					"image_url": "https://example.com/deploy.png",
					"alt_text": "Deploy chart"
				},
				"expand": true
			},
			{
				"type": "section",
				"block_id": "facts",
				"fields": [
					{
						"type": "mrkdwn",
						"text": "*Environment*\nprod",
						"verbatim": true
					},
					{
						"type": "mrkdwn",
						"text": "*Duration*\n42s"
					}
				]
			},
			{
				"type": "image",
				"image_url": "https://example.com/screenshot.png",
				"alt_text": "Deployment screenshot",
				"title": {
					"type": "plain_text",
					"text": "Deployment details",
					"emoji": true
				}
			},
			{
				"type": "context",
				"elements": [
					{
						"type": "image",
						"image_url": "https://example.com/icon.png",
						"alt_text": "App icon"
					},
					{
						"type": "mrkdwn",
						"text": "Generated by *servekit*"
					}
				]
			},
			{
				"type": "actions",
				"elements": [
					{
						"type": "button",
						"text": {
							"type": "plain_text",
							"text": "Open dashboard",
							"emoji": true
						},
						"action_id": "open_dashboard",
						"url": "https://example.com/deploys/123",
						"value": "deploy-123",
						"style": "primary",
						"accessibility_label": "Open deployment dashboard"
					}
				]
			}
		]
	}`))
}

func TestNewMessage_RejectsTooManyBlocks(t *testing.T) {
	blocks := make([]Block, 51)
	for i := range blocks {
		blocks[i] = NewDivider()
	}

	message, err := NewMessage("too many blocks", blocks...)

	td.CmpNil(t, message)
	td.Cmp(t, err, td.NotNil())
	td.Cmp(t, err.Error(), td.Contains("too many blocks"))
}

func TestBlockValidate_RejectsEmptyActionElements(t *testing.T) {
	block := NewActions()

	err := block.validate()

	td.Cmp(t, err, ErrNilBlockElements)
}
