name: Pull Request

on:  
  pull_request:
    paths-ignore:
      - '.github/workflows/pr.yml'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: go test
        run: go test -race -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: golangci-lint run
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=3m